### ISSUE TITLE
Documentation clarification

### ISSUE THREAD

**Issue by pyhedgehog** [RoccoMatano/ctwin32#2]
Can you add to README difference between this project and [pywin32-ctypes](https://github.com/enthought/pywin32-ctypes)?
You refer to [comtypes](https://github.com/enthought/comtypes), but not pywin32-ctypes.

**Comment by RoccoMatano** [comment]
[Done!](https://github.com/RoccoMatano/ctwin32/commit/d964a007619b72a47ea44546b63a1204d806f49d)
